CREATE TABLE IF NOT EXISTS KASIR (
   KASIR_ID INT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(20),
   EMAIL VARCHAR(20),
   PASSWORD CHAR(64)
);
CREATE TABLE IF NOT EXISTS PRODUK (
	PRODUK_ID INT AUTO_INCREMENT PRIMARY KEY,
	KODE_PRODUK VARCHAR(20),
    NAMA_PRODUK VARCHAR(20),
    KATEGORI VARCHAR(20),
    SATUAN VARCHAR(20),
    MODAL BIGINT,
    JUAL BIGINT
);
CREATE TABLE IF NOT EXISTS TRANSAKSI_PENJUALAN (
	TRANSAKSI_ID INT AUTO_INCREMENT PRIMARY KEY,
	JUMLAH INT,
    PRODUK_ID INT,
    NO_INVOICE INT,
    FOREIGN KEY(PRODUK_ID) REFERENCES PRODUK (PRODUK_ID),
    FOREIGN KEY(NO_INVOICE) REFERENCES INVOICE_PEMBELIAN (NO_INVOICE)
);
CREATE TABLE IF NOT EXISTS INVOICE_PEMBELIAN (
   NO_INVOICE INT,
   TANGGAL DATE,
   NAMA_PELANGGAN VARCHAR(20),
   NAMA_KASIR VARCHAR(20)
);